#!/usr/bin/env python

import argparse
import status
import json

def main():
  """Run the script."""
  parser = argparse.ArgumentParser(description = 'Summarize the status of a collection of builds.')
  parser.add_argument("configuration", help = 'Configuration file specifying the build jobs to check.')
  options = parser.parse_args()

  checker = status.Checker(options.configuration)
  print json.dumps(checker.update())

if __name__ == "__main__":
  main()
